#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$BaseURL = '',
    [string]$Destination = 'public'
)
. (Join-Path $PSScriptRoot 'runtime-common.ps1')
try {
    Initialize-MicuRuntime
    if ([IO.Path]::IsPathRooted($Destination)) { $outputPath = [IO.Path]::GetFullPath($Destination).TrimEnd('\') }
    else { $outputPath = [IO.Path]::GetFullPath((Join-Path $script:ProjectRoot $Destination)).TrimEnd('\') }
    $prefix = $script:ProjectRoot + '\'
    if (-not $outputPath.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) {
        throw '构建目录必须位于本项目内部，不能是项目根目录或外部路径。'
    }
    $relative = $outputPath.Substring($prefix.Length)
    $top = ($relative -split '\\')[0]
    $protected = @('content','layouts','assets','static','themes','tools','scripts','docs','archetypes','data','config','tests','.git','工作室logo','参考资料')
    if ($protected -contains $top) { throw '该目录属于项目源文件或素材目录，不能用作构建输出。' }
    if ($top -eq '.runtime' -and -not $relative.StartsWith('.runtime\builds\', [StringComparison]::OrdinalIgnoreCase)) {
        throw '.runtime 内的构建输出请放在 .runtime\builds\子目录，避免覆盖运行记录和日志。'
    }
    $ancestor = $outputPath
    while ($ancestor -ne $script:ProjectRoot) {
        if (Test-Path -LiteralPath $ancestor) {
            $entry = Get-Item -LiteralPath $ancestor -Force
            if (($entry.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
                throw '构建目录及其上级不能是符号链接或目录联接，避免清理到其他位置。'
            }
        }
        $ancestor = Split-Path -Parent $ancestor
    }
    $marker = Join-Path $outputPath '.micu-build-output'
    if (Test-Path -LiteralPath $outputPath) {
        $entries = @(Get-ChildItem -LiteralPath $outputPath -Force)
        if ($entries.Count -gt 0 -and -not (Test-Path -LiteralPath $marker -PathType Leaf)) {
            throw '目标目录已有文件且未标记为本项目的构建产物，请指定新的空目录。'
        }
    }
    else { New-Item -ItemType Directory -Path $outputPath -Force | Out-Null }
    if ($BaseURL) {
        $parsedUrl = $null
        if (-not [Uri]::TryCreate($BaseURL, [UriKind]::Absolute, [ref]$parsedUrl) -or $parsedUrl.Scheme -notin @('http','https')) {
            throw 'BaseURL 必须是包含 http:// 或 https:// 的完整网址。'
        }
        if (-not $BaseURL.EndsWith('/')) { $BaseURL += '/' }
    }
    # Hugo's cleanDestinationDir does not remove every obsolete rendered page.
    # Only an empty or previously marked directory reaches this point; its full
    # path and all ancestors have already been checked against the project root.
    foreach ($entry in @(Get-ChildItem -LiteralPath $outputPath -Recurse -Force)) {
        if (($entry.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
            throw '构建输出中存在符号链接或目录联接，请先核实并移除，脚本不会清理此目录。'
        }
    }
    foreach ($entry in @(Get-ChildItem -LiteralPath $outputPath -Force)) {
        Remove-Item -LiteralPath $entry.FullName -Recurse -Force
    }
    $arguments = @('--source', $script:ProjectRoot, '--destination', $outputPath, '--environment', 'production', '--buildDrafts=false', '--minify', '--cacheDir', (Join-Path $script:RuntimeDirectory 'cache'))
    if ($BaseURL) { $arguments += @('--baseURL', $BaseURL) }
    try {
        & $script:HugoExecutable @arguments
        $buildResult = $LASTEXITCODE
    }
    finally { 'Generated by scripts/build-site.ps1; safe to regenerate.' | Set-Content -LiteralPath $marker -Encoding UTF8 }
    if ($buildResult -ne 0) { throw ('Hugo 构建失败，退出码：' + $buildResult) }
    Write-Host ('生产构建完成：' + $outputPath)
    exit 0
}
catch {
    Write-Host ('构建失败：' + $_.Exception.Message) -ForegroundColor Red
    exit 1
}
